# Generated by Django 3.0 on 2020-03-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('p_desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('fund', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
