# Generated by Django 3.0 on 2020-03-07 03:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(null=True)),
                ('cname', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('status', models.IntegerField(null=True)),
                ('perform', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(null=True)),
                ('cid', models.IntegerField(null=True)),
                ('perform', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('education', multiselectfield.db.fields.MultiSelectField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('Graduate', 'Graduate'), ('Diploma', 'Diploma'), ('B.E', 'B.E'), ('B.Tech', 'B.Tech')], max_length=35)),
                ('experience', models.IntegerField(null=True)),
                ('industry', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('c', 'c'), ('java', 'java'), ('c++', 'c++'), ('python', 'python'), ('webdevelopment', 'webdevelopment'), ('andrioddevelopment', 'andrioddevelopment')], max_length=51)),
                ('course', multiselectfield.db.fields.MultiSelectField(choices=[('c', 'c'), ('java', 'java'), ('c++', 'c++'), ('python', 'python'), ('webdevelopment', 'webdevelopment'), ('andrioddevelopment', 'andrioddevelopment')], max_length=51)),
                ('applyjobs', multiselectfield.db.fields.MultiSelectField(choices=[('123', '123'), ('1234', '1234'), ('12345', '12345')], max_length=14)),
                ('totalProject', models.IntegerField(null=True)),
                ('english', models.CharField(max_length=200, null=True)),
                ('availability', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(default='', upload_to='student/images')),
            ],
        ),
    ]
