# Generated by Django 3.0 on 2020-03-06 10:26

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='devalappers', max_length=100)),
                ('desc', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='job_offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_desc', models.CharField(max_length=100)),
                ('skills_required', multiselectfield.db.fields.MultiSelectField(choices=[('c', 'c'), ('java', 'java'), ('c++', 'c++'), ('python', 'python'), ('androiddevelopment', 'androiddevelopment'), ('webdevelopment', 'webdevelopment')], max_length=51)),
                ('education', multiselectfield.db.fields.MultiSelectField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('Graduate', 'Graduate'), ('Diploma', 'Diploma'), ('B.E', 'B.E'), ('B.Tech', 'B.Tech')], max_length=35)),
                ('education_years', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lock.company')),
            ],
        ),
    ]
