# Generated by Django 3.0 on 2020-03-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_offers',
            name='vacancy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
