# Generated by Django 3.0 on 2020-03-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0002_job_offers_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
